# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'cksapp' do

pod 'GoogleMaps'

end

target 'cksappTests' do

end

target 'cksappUITests' do

end

