Country.create(name: "Argentina", photo: 1)
Country.create(name: "Australia", photo: 2)
Country.create(name: "Brazil", photo: 3)
Country.create(name: "Canada", photo: 4)
Country.create(name: "China", photo: 5)
Country.create(name: "Denmark", photo: 6)
Country.create(name: "Egypt", photo: 7)
Country.create(name: "Ethiopia", photo: 8)
Country.create(name: "Finland", photo: 9)
Country.create(name: "France", photo: 10)
Country.create(name: "Germany", photo: 11)
Country.create(name: "Great Britain", photo: 12)
Country.create(name: "Greece", photo: 13)
Country.create(name: "India", photo: 14)
Country.create(name: "Italy", photo: 15)
Country.create(name: "Japan", photo: 16)
Country.create(name: "South Korea", photo: 17)
Country.create(name: "Mexico", photo: 18)
Country.create(name: "Russia", photo: 19)
Country.create(name: "Sweden", photo: 20)
Country.create(name: "United States", photo: 21)

Location.create(title: "Olympic Stadium", lattitude: "35.6766643", longitude: "139.7157182", description: "Opening and Closing Ceremonies, Athletics, Football", ranking: 1, photo: 61)
Location.create(title: "Tokyo Metropolitan Gymnasium", lattitude: "35.6793961", longitude: "139.7097847", description: "Table Tennis", ranking: 2, photo: 62)
Location.create(title: "Yoyogi National Stadium", lattitude: "35.6672534", longitude: "139.6977478", description: "Handball", ranking: 3, photo: 63)
Location.create(title: "Nippon Budokan", lattitude: "35.6933175", longitude: "139.7476963", description: "Judo", ranking: 4, photo: 64)
Location.create(title: "Outer Imperial Gardens", lattitude: "35.6739249", longitude: "139.7529757", description: "Cycling (road)", ranking: 5, photo: 65)
Location.create(title: "Tokyo International Forum", lattitude: "35.6766572", longitude: "139.7621109", description: "Weightlifting", ranking: 6, photo: 66)
Location.create(title: "Kokugikan Arena", lattitude: "35.6771808", longitude: "139.7307617", description: "Boxing", ranking: 7, photo: 67)
Location.create(title: "Ariake Arena", lattitude: "35.6346701", longitude: "139.7395666", description: "Volleyball (indoor)", ranking: 8, photo: 68)
Location.create(title: "Olympic Gymnastic Center", lattitude: "NULL", longitude: "NULL", description: "Gymnastics", ranking: 9, photo: 69)
Location.create(title: "Ariake BMX Course", lattitude: "NULL", longitude: "NULL", description: "Cycling (BMX)", ranking: 10, photo: 70)
Location.create(title: "Ariake Tennis Park", lattitude: "35.6362392", longitude: "139.7866163", description: "Tennis", ranking: 11, photo: 71)
Location.create(title: "Odaiba Marine Park", lattitude: "NULL", longitude: "NULL", description: "Marathon swimming, Triathlon", ranking: 12, photo: 72)
Location.create(title: "Shiokaze Park", lattitude: "35.6240155", longitude: "139.7665912", description: "Beach volleyball", ranking: 13, photo: 73)
Location.create(title: "Seaside Park Hockey Stadium", lattitude: "35.602693", longitude: "139.7290888", description: "Hockey", ranking: 14, photo: 74)
Location.create(title: "Sea Forest Cross-Country Course", lattitude: "NULL", longitude: "NULL", description: "Equestrian (eventing, cross-country)", ranking: 15, photo: 75)
Location.create(title: "Sea Forest Waterway", lattitude: "NULL", longitude: "NULL", description: "Canoe-Kayak (sprint), Rowing", ranking: 16, photo: 76)
Location.create(title: "Canoe slalom venue", lattitude: "NULL", longitude: "NULL", description: "Canoe-Kayak (slalom)", ranking: 17, photo: 77)
Location.create(title: "Dream Island Archery Field", lattitude: "NULL", longitude: "NULL", description: "Archery", ranking: 18, photo: 78)
Location.create(title: "Olympic Aquatics Center", lattitude: "NULL", longitude: "NULL", description: "Aquatics (swimming, diving, synchronised swimming)", ranking: 19, photo: 79)
Location.create(title: "Tatsumi International Swimming Centre", lattitude: "35.6464739", longitude: "139.7617982", description: "Aquatics (waterpolo)", ranking: 20, photo: 80)
Location.create(title: "Equestrian Park", lattitude: "NULL", longitude: "NULL", description: "Equestrian (dressage, jumping, eventing)", ranking: 21, photo: 81)
Location.create(title: "Musashino Forest Sport Centre", lattitude: "NULL", longitude: "NULL", description: "Badminton, Modern Pentathlon (fencing)", ranking: 22, photo: 82)
Location.create(title: "Tokyo Stadium", lattitude: "35.6780862", longitude: "139.7127467", description: "Football, Modern Pentathlon (swimming, riding, running, shooting), Rugby", ranking: 23, photo: 83)
Location.create(title: "Saitama Super Arena", lattitude: "35.895081", longitude: "139.6285432", description: "Basketball", ranking: 24, photo: 84)
Location.create(title: "Asaka Shooting Range", lattitude: "35.7396529", longitude: "139.4323106", description: "Shooting", ranking: 25, photo: 85)
Location.create(title: "Kasumigaseki Country Club", lattitude: "35.8975939", longitude: "139.3972779", description: "Golf", ranking: 26, photo: 86)
Location.create(title: "Makuhari Messe", lattitude: "35.6467013", longitude: "140.0344653", description: "Fencing, Taekwondo, Wrestling", ranking: 27, photo: 87)
Location.create(title: "Enoshima Yacht Harbour", lattitude: "35.2989036", longitude: "139.4818721", description: "Sailing", ranking: 28, photo: 88)
Location.create(title: "Izu Velodrome", lattitude: "35.4006197", longitude: "138.5882584", description: "Cycling (track)", ranking: 29, photo: 89)
Location.create(title: "Izu Mountain Bike Course", lattitude: "NULL", longitude: "NULL", description: "Cycling (mountain bike)", ranking: 30, photo: 90)
Location.create(title: "Sapporo Dome", lattitude: "43.2989155", longitude: "143.7546776", description: "Football", ranking: 31, photo: 91)
Location.create(title: "Miyagi Stadium", lattitude: "38.3354508", longitude: "140.9495998", description: "Football", ranking: 32, photo: 92)
Location.create(title: "Saitama Stadium", lattitude: "35.9031344", longitude: "139.7154084", description: "Football", ranking: 33, photo: 93)
Location.create(title: "International Stadium Yokohama", lattitude: "35.5099504", longitude: "139.604205", description: "Football", ranking: 34, photo: 94)
Location.create(title: "Olympic Village（OV）", lattitude: "NULL", longitude: "NULL", description: "NULL", ranking: 35, photo: 95)
Location.create(title: "Tokyo International Exhibition Center　（IBC/MPC）", lattitude: "NULL", longitude: "NULL", description: "NULL", ranking: 36, photo: 96)

Player.create(name: "Usain Bolt", gender: "M", gamesList: "1,2,4", country: 21, photo: 31)
Player.create(name: "Serena Williams", gender: "W", gamesList: "Tennis", country: 21, photo: 32)
Player.create(name: "Bradley Wiggins", gender: "M", gamesList: "Road Cycling", country: 12, photo: 33)
Player.create(name: "Robert Scheidt", gender: "M", gamesList: "Sailing", country: 3, photo: 34)
Player.create(name: "Tamika Catchings", gender: "W", gamesList: "Basketball", country: 21, photo: 35)
Player.create(name: "Yelena Isinbaeva", gender: "W", gamesList: "Athletics", country: 19, photo: 36)
Player.create(name: "Lin Dan", gender: "M", gamesList: "Badminton", country: 5, photo: 37)
Player.create(name: "Federica Pellegrini", gender: "W", gamesList: "Swimming", country: 15, photo: 38)
Player.create(name: "Tiago Camilo", gender: "M", gamesList: "Judo", country: 3, photo: 39)
Player.create(name: "Lauren Jackson", gender: "W", gamesList: "Basketball", country: 2, photo: 40)
